# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Trigger workflow when files inside backend folder are changed
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'  # Trigger workflow when files inside backend folder are changed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Ensure environment variables are set
    - name: Set environment variables
      run: |
        echo "MONGO_URI=$MONGO_URI" >> $GITHUB_ENV
        echo "NODE_ENV=test" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm ci

    - name: Build the project (if applicable)
      run: npm run build --if-present

    - name: Run tests
      run: npm test
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }} # Example of using secrets for environment variables

    - name: Debugging - Check node version and npm versions
      run: |
        node -v
        npm -v
        npm ls
