# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - main
    # paths:
    #   - 'backend/**'  # Trigger workflow when files inside the backend folder are changed
  pull_request:
    branches:
      - main
    # paths:
    #   - 'backend/**'  # Trigger workflow when files inside the backend folder are changed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # Node versions to test with

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Change to the backend directory before setting up Node.js and running tests
    - name: Change to backend directory
      run: cd backend

    # Use Node.js ${{ matrix.node-version }} for the backend directory
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install backend dependencies
    - name: Install backend dependencies
      run: |
        cd backend  # Ensure we're in the backend directory
        npm ci  # This will install dependencies from package-lock.json

    # Run build if there's a build script defined
    - name: Build the backend project (if applicable)
      run: |
        cd backend  # Ensure we're in the backend directory
        npm run start --if-present

    # Run tests within the backend directory
    - name: Run tests for backend
      run: |
        cd backend  # Ensure we're in the backend directory
        npm run test

    - name: Debugging - Check node version and npm versions
      run: |
        cd backend  # Ensure we're in the backend directory
        node -v
        npm -v
        npm ls backend
